apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: a-tsdb-remote-write
  namespace: prometheus
spec:
  encryptedData:
    password: AgCcD89oKmUU2VZvGYWo0PKf/Z5KwXvPhVIVS1cM1PCrm5/wdtj+wLiV8LNTBseJnPNS6fDcGU9GDRYplxWdv/Gt72up9lSGphgRH4TuII6oWcmraVBbM7+s48fmsRKUtBofqarfFwyA9RZCSR6WApAPmfJphVaH8HgrLKJRheHsiLJ5/wCUFDlMHiSnbxunmXNpzqmYMa0pCdMIM6fGkFRc8YbvWM5sGUm5J3YVFzKECJBGx07i6XVjxoFz8pN5i/ywkjbWWZ4xp06HP0+Mck6n7Th7U5zhw9zYqCgUXnh+ax+meEoXLiCheTWsYegD9Aft6g5hHNsfbtDTCXn0haDEVLCQyz2zpI4BYE3NdzXlHTNOWfGa5zhgV/uIpxa3uWt6V9a9zV6rzcQodQP82Zu3NRe49ukRg84pykMN8q9tsyIKXbVkhL/d4omewpwJFTL1AyOOWmiSC2khl8EdQe7fazrCZIujD6KEy+O2We56ouLPBXsXMPcG65joVEnpnHhAumm+Ke2bwqjayCNjGpTLZNXlV78PmQgK4tvdoOmoBGGBPdez5b56s6p6joDDw3UIcA3jC+cEqTZiN6VuGJ04BNdl94n7m+2ZkERQt1amLeUxFKq5HB36WT34e9sgfb5uutEWZDziv2qHfxuKi4RzlCMwT8w6KtGlTbYTaY7/XAtPWkMCPG1F5C2He2N8RmFn
    username: AgCX6xuz44X9rDaUBS7nRPxob9YoAMbO0SdYUcUHFOSuxn1iOaIRaNLKIEDO/4p3rABS2kkyScZ0j1CO7uWUnK+UAxzz2Q0JRqT+guuioaXVR3Rh18CE1wmTa7h+t8o/P0K7h2pJa/X8jSbJAFgfXTdi/0vubblOtw0WqJYwnryRpA0VZ24XyUxR0PivqVsTg3p3p/mOEVk60If7nzFFRHicNi+Rhz8KxL3y9dh2Ucp8UfkHCBojc4nlTkseb3ZCZE6DLEw6VCO4JuuO4gYtisJ5OpO9Xhxrx5OuDv10z9IO4sl5iR1wva7vbz8HlkJp1mntWvHT898UN1/Tbnax3ziP9tIPpDXGGlN17agwEnXdeg79keR7wfEksUUvsdgyaql/pj1VMR/ziQVAazaN9iDj6uvU5UQKxJlieye/5G7I54To34rxISBZZ6eUeSgkaXBW1XKL+n4Nyaf4gGVAB8vavX6QBs7rXHoBSRh8eksLS3DuNhO/V1ntHR8K9jZXvBYe2uykd2SaXZPgvX5AFTuy0ykvpeGq1S9d7HRKM3N+Ow30BWN+2fnSVvrrTPHmP94fFCbNJaAqFvBzFuCY9PCvDTER+3VxDF7QfQoDTuz5Te4bAQpmh/Fm6OchUVBn8mvJsfxvXFHXU1UslbjNLe06yCdYHwCn6ZGGou0zPP8bPWuzg8kJbvdGlGSWJh8ypbsJ
  template:
    metadata:
      creationTimestamp: null
      name: a-tsdb-remote-write
      namespace: prometheus

