karte:
  enabled: true
  namespaceOverride: "default"

  # These services are not directly used in the demo story, but they all talk to each other and serve to add some
  # complexity to the graph.
  additionalServices:
    - "currant"
    - "acai"
    - "agarita"
    - "amla"
    - "bane"
    - "mul"
    - "boysen"
    - "buffalo"
    - "caper"

  problemStateEnabled: true

kube-prometheus-stack:
  enabled: false
  namespaceOverride: "prometheus"

  kube-state-metrics:
    namespaceOverride: "prometheus"

  prometheus-node-exporter:
    namespaceOverride: "prometheus"

  grafana:
    enabled: false
    namespaceOverride: "prometheus"
    ingress:
      enabled: true
      hosts:
        - "localhost"
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: http://host.docker.internal:8428/api/v1/write

  # Prevent istio from interfering with the Prometheus operator install. Without this, `helm install` will timeout
  # waiting for an installation job.
  prometheusOperator:
    admissionWebhooks:
      patch:
        podAnnotations:
          sidecar.istio.io/inject: "false"

  kubelet:
    serviceMonitor:
      # When running on kind, cAdvisor will discover metrics via both the docker container that kind's node run in
      # and through Kubernetes. The result is that container metrics will be duplicated which causes problems.
      # To avoid that, drop the metrics sourced from kind's docker container.
      #
      # For more, see: https://app.clubhouse.io/asserts/story/2648/
      cAdvisorMetricRelabelings:
       - sourceLabels: [id]
         regex: \/docker\/.*
         action: drop

  # Monitoring Kubernetes's control plane produces a lot of metrics which aren't needed for the demo, so turn it off.
  kubeApiServer:
    enabled: false


fluent-bit:
  enabled: true
  # Default values for fluent-bit.
  # kind -- DaemonSet or Deployment
  kind: DaemonSet
  image:
    repository: fluent/fluent-bit
    pullPolicy: IfNotPresent
    tag: 1.5.3
  nameOverride: "fluent-bit"
  fullnameOverride: "fluent-bit"
  service:
    type: ClusterIP
    port: 2020
  serviceMonitor:
    enabled: true
    namespace: default
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit

postgresql:
  postgresqlDatabase: "karte"
  postgresqlPassword: "F.t7oQs*aWfHYjzB_qvG7upjM!hXb9g*!"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: "karte-eks"
      relabelings:
        - action: replace
          sourceLabels: [job]
          replacement: "karte-eks-postgresql"
          targetLabel: "job"
      metricRelabelings:
        - action: replace
          sourceLabels: [namespace]
          regex: "default"
          replacement: "prod"
          targetLabel: "asserts_env"
        - action: replace
          sourceLabels: [ namespace ]
          regex: "default"
          replacement: "us-west-2"
          targetLabel: "asserts_site"
