karte:
  enabled: true
  namespaceOverride: "default"

  # These services are not directly used in the demo story, but they all talk to each other and serve to add some
  # complexity to the graph.
  additionalServices:
    - "currant"
    - "acai"
    - "agarita"
    - "amla"
    - "bane"
    - "mul"
    - "boysen"
    - "buffalo"
    - "caper"

  problemStateEnabled: true

kube-prometheus-stack:
  namespaceOverride: "prometheus"

  kube-state-metrics:
    namespaceOverride: "prometheus"

  prometheus-node-exporter:
    namespaceOverride: "prometheus"

  grafana:
    enabled: false
    namespaceOverride: "prometheus"
    ingress:
      enabled: true
      hosts:
        - "localhost"
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: http://host.docker.internal:8428/api/v1/write

  # Prevent istio from interfering with the Prometheus operator install. Without this, `helm install` will timeout
  # waiting for an installation job.
  prometheusOperator:
    admissionWebhooks:
      patch:
        podAnnotations:
          sidecar.istio.io/inject: "false"

  kubelet:
    serviceMonitor:
      # When running on kind, cAdvisor will discover metrics via both the docker container that kind's node run in
      # and through Kubernetes. The result is that container metrics will be duplicated which causes problems.
      # To avoid that, drop the metrics sourced from kind's docker container.
      #
      # For more, see: https://app.clubhouse.io/asserts/story/2648/
      cAdvisorMetricRelabelings:
       - sourceLabels: [id]
         regex: \/docker\/.*
         action: drop

  # Monitoring Kubernetes's control plane produces a lot of metrics which aren't needed for the demo, so turn it off.
  kubeApiServer:
    enabled: false


fluent-bit:
  # Default values for fluent-bit.
  # kind -- DaemonSet or Deployment
  kind: DaemonSet
  image:
    repository: fluent/fluent-bit
    pullPolicy: IfNotPresent
    tag: 1.5.3
  nameOverride: "fluent-bit"
  fullnameOverride: "fluent-bit"
  service:
    type: ClusterIP
    port: 2020
  serviceMonitor:
    enabled: true
    namespace: default
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit
  config:
    ## https://docs.fluentbit.io/manual/service
    service: |
      [SERVICE]
          Flush 1
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name                    tail
          Tag                     kube.*
          Path                    /var/log/containers/authv2-*.log
          Parser                  docker
          DB                      /var/log/flb_kube.db
          Mem_Buf_Limit           5MB
          Refresh_Interval        10
    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name                    kubernetes
          Match                   kube.*
          Merge_Log_Key           log_processed
          Merge_Log               On
          Keep_Log                On
          Annotations             Off
          Labels                  Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
      [FILTER]
          Name                nest
          Match               *
          Operation lift
          Nested_under log_processed
          Add_prefix log_proc_
      # Filter out log messages that didn't come in the JSON format used by karte, in which the short log
      # message is in the `message` property.
      [FILTER]
          Name                grep
          Match               *
          regex               log_proc_message .+
      [FILTER]
          Name                nest
          Match               kube.*
          Operation lift
          Nested_under kubernetes
          Add_prefix   kubernetes_
      [FILTER]
          Name                modify
          Match               kube.*
          Copy     kubernetes_pod_name pod
          Copy     kubernetes_namespace_name namespace
          Copy     kubernetes_container_name container
          Copy     kubernetes_container_name tag
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [FILTER]
          Name                modify
          Match               *
          Remove_wildcard kubernetes
      [FILTER]
          Name                modify
          Match               *
          Set     cluster     kind-control-plane
      [OUTPUT]
          Name                    gelf
          Match                   *
          Host                    graylog-tcp-internal.monitoring.asserts.ai
          Port                    12201
          Mode                    tcp
          Gelf_Timestamp_Key      time
          Gelf_Host_Key           stream
          Gelf_Short_Message_Key  log_proc_message
