apiVersion: v2
name: karte
description: A demo application for Asserts
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: kube-prometheus-stack
    version: "11.1.6"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: fluent-bit
    version: "0.12.3"
    repository: "https://fluent.github.io/helm-charts"
