version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: kafka
      dockerfile: Dockerfile
    hostname: kafka
    container_name: kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "Topic3:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  spring_boot:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - kafka
      - zookeeper
