apiVersion: v2
name: orderplacement
description: A Kafka & Zookeeper demo app for Asserts
type: application

# This is the chart version.
version: 1.1.0

# This is the version number of the application being deployed.
appVersion: "latest"

dependencies: # A list of the chart requirements (optional)
