server:
  port: 8091
  servlet:
    context-path: "/ordeplacement"

# enable Prometheus metrics
management:
  endpoint:
    prometheus:
      enabled: true
    web:
      exposure:
        include: "info, health, prometheus"
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot
    bootstrap-servers: kafka:9092


topic:
  produce: orders

