= Kafka

== Kafka Exporter Metrics

  go_gc_duration_seconds{quantile="0"} 0
  go_gc_duration_seconds{quantile="0.25"} 0
  go_gc_duration_seconds{quantile="0.5"} 0
  go_gc_duration_seconds{quantile="0.75"} 0
  go_gc_duration_seconds{quantile="1"} 0
  go_gc_duration_seconds_sum 0
  go_gc_duration_seconds_count 0

  go_goroutines 11

  go_memstats_alloc_bytes 954480
  go_memstats_alloc_bytes_total 954480
  go_memstats_buck_hash_sys_bytes 1.443014e+06
  go_memstats_frees_total 373
  go_memstats_gc_sys_bytes 169984
  go_memstats_heap_alloc_bytes 954480
  go_memstats_heap_idle_bytes 548864
  go_memstats_heap_inuse_bytes 2.138112e+06
  go_memstats_heap_objects 7124
  go_memstats_heap_released_bytes_total 0
  go_memstats_heap_sys_bytes 2.686976e+06
  go_memstats_last_gc_time_seconds 0
  go_memstats_lookups_total 22
  go_memstats_mallocs_total 7497
  go_memstats_mcache_inuse_bytes 13888
  go_memstats_mcache_sys_bytes 16384
  go_memstats_mspan_inuse_bytes 31768
  go_memstats_mspan_sys_bytes 32768
  go_memstats_next_gc_bytes 4.473924e+06
  go_memstats_other_sys_bytes 797746
  go_memstats_stack_inuse_bytes 458752
  go_memstats_stack_sys_bytes 458752
  go_memstats_sys_bytes 5.605624e+06
  
  kafka_brokers 1

  kafka_consumergroup_current_offset{consumergroup="boot",partition="0",topic="Topic3"} 7412
  kafka_consumergroup_lag{consumergroup="boot",partition="0",topic="Topic3"} 0
  
  kafka_exporter_build_info{branch="HEAD",goversion="go1.10.3",revision="830660212e6c109e69dcb1cb58f5159fe3b38903",version="1.2.0"} 1
  
  kafka_topic_partition_current_offset{partition="0",topic="Topic3"} 7412
  kafka_topic_partition_in_sync_replica{partition="0",topic="Topic3"} 1
  kafka_topic_partition_leader{partition="0",topic="Topic3"} 0
  kafka_topic_partition_leader_is_preferred{partition="0",topic="Topic3"} 1
  kafka_topic_partition_oldest_offset{partition="0",topic="Topic3"} 0
  kafka_topic_partition_replicas{partition="0",topic="Topic3"} 1
  kafka_topic_partition_under_replicated_partition{partition="0",topic="Topic3"} 0
  kafka_topic_partitions{topic="Topic3"} 1
  
  kafka_topic_partition_current_offset{partition="0",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="1",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="10",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="11",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="12",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="13",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="14",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="15",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="16",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="17",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="18",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="19",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="2",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="20",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="21",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="22",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="23",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="24",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="25",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="26",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="27",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="28",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="29",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="3",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="30",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="31",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="32",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="33",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="34",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="35",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="36",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="37",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="38",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="39",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="4",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="40",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="41",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="42",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="43",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="44",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="45",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="46",topic="__consumer_offsets"} 7407
  kafka_topic_partition_current_offset{partition="47",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="48",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="49",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="5",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="6",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="7",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="8",topic="__consumer_offsets"} 0
  kafka_topic_partition_current_offset{partition="9",topic="__consumer_offsets"} 0

  kafka_topic_partition_in_sync_replica{partition="0",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="1",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="10",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="11",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="12",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="13",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="14",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="15",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="16",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="17",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="18",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="19",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="2",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="20",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="21",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="22",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="23",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="24",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="25",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="26",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="27",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="28",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="29",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="3",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="30",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="31",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="32",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="33",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="34",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="35",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="36",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="37",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="38",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="39",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="4",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="40",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="41",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="42",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="43",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="44",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="45",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="46",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="47",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="48",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="49",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="5",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="6",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="7",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="8",topic="__consumer_offsets"} 1
  kafka_topic_partition_in_sync_replica{partition="9",topic="__consumer_offsets"} 1

  kafka_topic_partition_leader{partition="0",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="1",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="10",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="11",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="12",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="13",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="14",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="15",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="16",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="17",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="18",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="19",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="2",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="20",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="21",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="22",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="23",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="24",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="25",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="26",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="27",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="28",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="29",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="3",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="30",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="31",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="32",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="33",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="34",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="35",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="36",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="37",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="38",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="39",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="4",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="40",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="41",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="42",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="43",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="44",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="45",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="46",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="47",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="48",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="49",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="5",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="6",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="7",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="8",topic="__consumer_offsets"} 0
  kafka_topic_partition_leader{partition="9",topic="__consumer_offsets"} 0

  kafka_topic_partition_leader_is_preferred{partition="0",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="1",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="10",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="11",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="12",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="13",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="14",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="15",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="16",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="17",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="18",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="19",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="2",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="20",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="21",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="22",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="23",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="24",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="25",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="26",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="27",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="28",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="29",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="3",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="30",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="31",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="32",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="33",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="34",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="35",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="36",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="37",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="38",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="39",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="4",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="40",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="41",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="42",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="43",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="44",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="45",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="46",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="47",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="48",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="49",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="5",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="6",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="7",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="8",topic="__consumer_offsets"} 1
  kafka_topic_partition_leader_is_preferred{partition="9",topic="__consumer_offsets"} 1

  kafka_topic_partition_oldest_offset{partition="0",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="1",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="10",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="11",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="12",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="13",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="14",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="15",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="16",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="17",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="18",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="19",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="2",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="20",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="21",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="22",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="23",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="24",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="25",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="26",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="27",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="28",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="29",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="3",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="30",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="31",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="32",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="33",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="34",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="35",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="36",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="37",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="38",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="39",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="4",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="40",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="41",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="42",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="43",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="44",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="45",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="46",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="47",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="48",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="49",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="5",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="6",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="7",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="8",topic="__consumer_offsets"} 0
  kafka_topic_partition_oldest_offset{partition="9",topic="__consumer_offsets"} 0

  kafka_topic_partition_replicas{partition="0",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="1",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="10",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="11",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="12",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="13",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="14",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="15",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="16",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="17",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="18",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="19",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="2",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="20",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="21",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="22",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="23",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="24",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="25",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="26",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="27",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="28",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="29",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="3",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="30",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="31",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="32",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="33",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="34",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="35",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="36",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="37",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="38",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="39",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="4",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="40",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="41",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="42",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="43",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="44",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="45",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="46",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="47",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="48",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="49",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="5",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="6",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="7",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="8",topic="__consumer_offsets"} 1
  kafka_topic_partition_replicas{partition="9",topic="__consumer_offsets"} 1

  kafka_topic_partition_under_replicated_partition{partition="0",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="1",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="10",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="11",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="12",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="13",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="14",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="15",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="16",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="17",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="18",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="19",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="2",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="20",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="21",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="22",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="23",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="24",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="25",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="26",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="27",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="28",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="29",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="3",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="30",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="31",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="32",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="33",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="34",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="35",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="36",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="37",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="38",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="39",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="4",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="40",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="41",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="42",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="43",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="44",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="45",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="46",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="47",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="48",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="49",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="5",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="6",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="7",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="8",topic="__consumer_offsets"} 0
  kafka_topic_partition_under_replicated_partition{partition="9",topic="__consumer_offsets"} 0

  kafka_topic_partitions{topic="__consumer_offsets"} 50

  process_cpu_seconds_total 0.1
  process_max_fds 1.048576e+06
  process_open_fds 9
  process_resident_memory_bytes 7.749632e+06
  process_start_time_seconds 1.61542529114e+09
  process_virtual_memory_bytes 1.3963264e+07