{{- if (.Capabilities.APIVersions.Has "bitnami.com/v1alpha1") }}
{{ range $i, $tenant := .Values.tenants }}
{{- if $tenant.auth_enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $tenant.name }}-tsdb-remote-write
{{- if index $.Values "kube-prometheus-stack" "namespaceOverride" }}
  namespace: {{ index $.Values "kube-prometheus-stack" "namespaceOverride" }}
{{- else }}
  namespace: {{ $.Release.Namespace }} 
{{- end }}
spec:
  encryptedData:
    password: {{ $tenant.password }}
    username: {{ $tenant.username }}
{{- end }}
{{- end }}
{{- end }}
