= SpringBoot-Kafka-App

== JMX Metrics

    jmx_config_reload_failure_created 1.615425252018E9
    jmx_config_reload_failure_total 0.0
    jmx_config_reload_success_created 1.615425252016E9
    jmx_config_reload_success_total 0.0
    
    jmx_exporter_build_info{version="0.15.0",name="jmx_prometheus_javaagent",} 1.0
    
    jmx_scrape_cached_beans 0.0
    jmx_scrape_duration_seconds 0.0347254
    jmx_scrape_error 0.0
    
    jvm_buffer_pool_capacity_bytes{pool="direct",} 187164.0
    jvm_buffer_pool_capacity_bytes{pool="mapped",} 0.0
    jvm_buffer_pool_used_buffers{pool="direct",} 11.0
    jvm_buffer_pool_used_buffers{pool="mapped",} 0.0
    jvm_buffer_pool_used_bytes{pool="direct",} 187164.0
    jvm_buffer_pool_used_bytes{pool="mapped",} 0.0
    
    jvm_classes_loaded 8848.0
    jvm_classes_loaded_total 8848.0
    jvm_classes_unloaded_total 0.0
    
    jvm_gc_collection_seconds_count{gc="PS MarkSweep",} 2.0
    jvm_gc_collection_seconds_count{gc="PS Scavenge",} 13.0
    jvm_gc_collection_seconds_sum{gc="PS MarkSweep",} 0.069
    jvm_gc_collection_seconds_sum{gc="PS Scavenge",} 0.21
    
    jvm_info{runtime="OpenJDK Runtime Environment",vendor="Oracle Corporation",version="1.8.0_111-8u111-b14-2~bpo8+1-b14",} 1.0
    
    jvm_memory_bytes_committed{area="heap",} 1.007681536E9
    jvm_memory_bytes_committed{area="nonheap",} 8.126464E7
    jvm_memory_bytes_init{area="heap",} 2.64241152E8
    jvm_memory_bytes_init{area="nonheap",} 2555904.0
    jvm_memory_bytes_max{area="heap",} 3.733979136E9
    jvm_memory_bytes_max{area="nonheap",} -1.0
    jvm_memory_bytes_used{area="heap",} 2.72372744E8
    jvm_memory_bytes_used{area="nonheap",} 7.60024E7
    
    jvm_memory_pool_allocated_bytes_created{pool="Code Cache",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_created{pool="Compressed Class Space",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_created{pool="Metaspace",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_created{pool="PS Eden Space",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_created{pool="PS Old Gen",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_created{pool="PS Survivor Space",} 1.615425253053E9
    jvm_memory_pool_allocated_bytes_total{pool="Code Cache",} 2.1997696E7
    jvm_memory_pool_allocated_bytes_total{pool="Compressed Class Space",} 5747384.0
    jvm_memory_pool_allocated_bytes_total{pool="Metaspace",} 4.8225408E7
    jvm_memory_pool_allocated_bytes_total{pool="PS Eden Space",} 6.126627104E9
    jvm_memory_pool_allocated_bytes_total{pool="PS Old Gen",} 2.6127328E7
    jvm_memory_pool_allocated_bytes_total{pool="PS Survivor Space",} 3.5576856E7
    jvm_memory_pool_bytes_committed{pool="Code Cache",} 2.228224E7
    jvm_memory_pool_bytes_committed{pool="Compressed Class Space",} 6553600.0
    jvm_memory_pool_bytes_committed{pool="Metaspace",} 5.24288E7
    jvm_memory_pool_bytes_committed{pool="PS Eden Space",} 8.89716736E8
    jvm_memory_pool_bytes_committed{pool="PS Old Gen",} 1.17440512E8
    jvm_memory_pool_bytes_committed{pool="PS Survivor Space",} 524288.0
    jvm_memory_pool_bytes_init{pool="Code Cache",} 2555904.0
    jvm_memory_pool_bytes_init{pool="Compressed Class Space",} 0.0
    jvm_memory_pool_bytes_init{pool="Metaspace",} 0.0
    jvm_memory_pool_bytes_init{pool="PS Eden Space",} 6.6060288E7
    jvm_memory_pool_bytes_init{pool="PS Old Gen",} 1.76160768E8
    jvm_memory_pool_bytes_init{pool="PS Survivor Space",} 1.1010048E7
    jvm_memory_pool_bytes_max{pool="Code Cache",} 2.5165824E8
    jvm_memory_pool_bytes_max{pool="Compressed Class Space",} 1.073741824E9
    jvm_memory_pool_bytes_max{pool="Metaspace",} -1.0
    jvm_memory_pool_bytes_max{pool="PS Eden Space",} 1.380974592E9
    jvm_memory_pool_bytes_max{pool="PS Old Gen",} 2.800746496E9
    jvm_memory_pool_bytes_max{pool="PS Survivor Space",} 524288.0
    jvm_memory_pool_bytes_used{pool="Code Cache",} 2.2025088E7
    jvm_memory_pool_bytes_used{pool="Compressed Class Space",} 5747384.0
    jvm_memory_pool_bytes_used{pool="Metaspace",} 4.8229928E7
    jvm_memory_pool_bytes_used{pool="PS Eden Space",} 2.45884968E8
    jvm_memory_pool_bytes_used{pool="PS Old Gen",} 2.6127328E7
    jvm_memory_pool_bytes_used{pool="PS Survivor Space",} 360448.0
    
    jvm_threads_current 34.0
    jvm_threads_daemon 27.0
    jvm_threads_deadlocked 0.0
    jvm_threads_deadlocked_monitor 0.0
    jvm_threads_peak 34.0
    jvm_threads_started_total 38.0
    jvm_threads_state{state="BLOCKED",} 0.0
    jvm_threads_state{state="NEW",} 0.0
    jvm_threads_state{state="RUNNABLE",} 9.0
    jvm_threads_state{state="TERMINATED",} 0.0
    jvm_threads_state{state="TIMED_WAITING",} 7.0
    jvm_threads_state{state="WAITING",} 18.0
    
    kafka_consumer_commit_id_info{commit_id="62abe01bee039651",clientId="consumer-boot-1",} 1.0
    
    kafka_consumer_connection_close_total{clientId="consumer-boot-1",} 14.0
    kafka_consumer_connection_count{clientId="consumer-boot-1",} 2.0
    kafka_consumer_connection_creation_total{clientId="consumer-boot-1",} 3.0
    
    kafka_consumer_coordinator_commit_latency_avg{clientId="consumer-boot-1",} 1.1333333333333333
    kafka_consumer_coordinator_commit_total{clientId="consumer-boot-1",} 2226.0
    kafka_consumer_coordinator_failed_rebalance_total{clientId="consumer-boot-1",} 1.0
    kafka_consumer_coordinator_heartbeat_total{clientId="consumer-boot-1",} 741.0
    kafka_consumer_coordinator_join_time_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_join_total{clientId="consumer-boot-1",} 1.0
    kafka_consumer_coordinator_last_heartbeat_seconds_ago{clientId="consumer-boot-1",} 0.0
    kafka_consumer_coordinator_last_rebalance_seconds_ago{clientId="consumer-boot-1",} 2224.0
    kafka_consumer_coordinator_partition_assigned_latency_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_partition_lost_latency_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_partition_revoked_latency_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_rebalance_latency_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_rebalance_latency_total{clientId="consumer-boot-1",} 73.0
    kafka_consumer_coordinator_rebalance_total{clientId="consumer-boot-1",} 1.0
    kafka_consumer_coordinator_sync_time_avg{clientId="consumer-boot-1",} NaN
    kafka_consumer_coordinator_sync_total{clientId="consumer-boot-1",} 1.0
    
    kafka_consumer_failed_authentication_total{clientId="consumer-boot-1",} 0.0
    kafka_consumer_failed_reauthentication_total{clientId="consumer-boot-1",} 0.0
    
    kafka_consumer_fetch_manager_bytes_consumed_total{clientId="consumer-boot-1",topic="Topic3",} 40068.0
    kafka_consumer_fetch_manager_bytes_consumed_total{clientId="consumer-boot-1",} 40068.0
    kafka_consumer_fetch_manager_fetch_latency_avg{clientId="consumer-boot-1",} 499.640625
    kafka_consumer_fetch_manager_fetch_size_avg{clientId="consumer-boot-1",topic="Topic3",} 18.0
    kafka_consumer_fetch_manager_fetch_size_avg{clientId="consumer-boot-1",} 18.0
    kafka_consumer_fetch_manager_fetch_throttle_time_avg{clientId="consumer-boot-1",} 0.0
    kafka_consumer_fetch_manager_fetch_total{clientId="consumer-boot-1",} 4455.0
    kafka_consumer_fetch_manager_preferred_read_replica{clientId="consumer-boot-1",partition="0",topic="Topic3",} -1.0
    kafka_consumer_fetch_manager_records_consumed_total{clientId="consumer-boot-1",topic="Topic3",} 2226.0
    kafka_consumer_fetch_manager_records_consumed_total{clientId="consumer-boot-1",} 2226.0
    kafka_consumer_fetch_manager_records_lag_avg{clientId="consumer-boot-1",partition="0",topic="Topic3",} 0.0
    kafka_consumer_fetch_manager_records_lag{clientId="consumer-boot-1",partition="0",topic="Topic3",} 0.0
    kafka_consumer_fetch_manager_records_lag{clientId="consumer-boot-1",partition="0",topic="Topic3",} 0.0
    kafka_consumer_fetch_manager_records_lead_avg{clientId="consumer-boot-1",partition="0",topic="Topic3",} 7871.5
    kafka_consumer_fetch_manager_records_lead{clientId="consumer-boot-1",partition="0",topic="Topic3",} 7842.0
    kafka_consumer_fetch_manager_records_lead{clientId="consumer-boot-1",partition="0",topic="Topic3",} 7901.0
    kafka_consumer_fetch_manager_records_per_request_avg{clientId="consumer-boot-1",topic="Topic3",} 1.0
    kafka_consumer_fetch_manager_records_per_request_avg{clientId="consumer-boot-1",} 1.0
    
    kafka_consumer_incoming_byte_total{clientId="consumer-boot-1",} 477922.0
    
    kafka_consumer_io_ratio{clientId="consumer-boot-1",} 5.706589348192303E-4
    kafka_consumer_io_time_ns_avg{clientId="consumer-boot-1",} 53057.530120481926
    kafka_consumer_io_wait_ratio{clientId="consumer-boot-1",} 1.0030850913567448
    kafka_consumer_io_wait_time_ns_avg{clientId="consumer-boot-1",} 9.326274277108434E7
    kafka_consumer_io_waittime_total{clientId="consumer-boot-1",} 2.2487295059E12
    kafka_consumer_iotime_total{clientId="consumer-boot-1",} 1.5323058E9
    
    kafka_consumer_last_poll_seconds_ago{clientId="consumer-boot-1",} 0.0
    
    kafka_consumer_network_io_total{clientId="consumer-boot-1",} 15153.0
    
    kafka_consumer_node_incoming_byte_total{clientId="consumer-boot-1",nodeId="node--1",} 565.0
    kafka_consumer_node_incoming_byte_total{clientId="consumer-boot-1",nodeId="node-0",} 395690.0
    kafka_consumer_node_incoming_byte_total{clientId="consumer-boot-1",nodeId="node-2147483647",} 81667.0
    
    kafka_consumer_node_outgoing_byte_total{clientId="consumer-boot-1",nodeId="node--1",} 98.0
    kafka_consumer_node_outgoing_byte_total{clientId="consumer-boot-1",nodeId="node-0",} 374657.0
    kafka_consumer_node_outgoing_byte_total{clientId="consumer-boot-1",nodeId="node-2147483647",} 341747.0
    
    kafka_consumer_node_request_latency_avg{clientId="consumer-boot-1",nodeId="node--1",} NaN
    kafka_consumer_node_request_latency_avg{clientId="consumer-boot-1",nodeId="node-0",} NaN
    kafka_consumer_node_request_latency_avg{clientId="consumer-boot-1",nodeId="node-2147483647",} NaN
    
    kafka_consumer_node_request_size_avg{clientId="consumer-boot-1",nodeId="node--1",} NaN
    kafka_consumer_node_request_size_avg{clientId="consumer-boot-1",nodeId="node-0",} 84.0
    kafka_consumer_node_request_size_avg{clientId="consumer-boot-1",nodeId="node-2147483647",} 114.69565217391305
    
    kafka_consumer_node_request_total{clientId="consumer-boot-1",nodeId="node--1",} 2.0
    kafka_consumer_node_request_total{clientId="consumer-boot-1",nodeId="node-0",} 4465.0
    kafka_consumer_node_request_total{clientId="consumer-boot-1",nodeId="node-2147483647",} 2972.0
    kafka_consumer_node_response_total{clientId="consumer-boot-1",nodeId="node--1",} 2.0
    kafka_consumer_node_response_total{clientId="consumer-boot-1",nodeId="node-0",} 4464.0
    kafka_consumer_node_response_total{clientId="consumer-boot-1",nodeId="node-2147483647",} 2972.0
    
    kafka_consumer_outgoing_byte_total{clientId="consumer-boot-1",} 716502.0
    
    kafka_consumer_poll_idle_ratio_avg{clientId="consumer-boot-1",} 0.49956063929454464
    
    kafka_consumer_reauthentication_latency_avg{clientId="consumer-boot-1",} NaN
    
    kafka_consumer_request_size_avg{clientId="consumer-boot-1",} 96.3859649122807
    kafka_consumer_request_total{clientId="consumer-boot-1",} 7439.0
    
    kafka_consumer_response_total{clientId="consumer-boot-1",} 7438.0
    
    kafka_consumer_select_total{clientId="consumer-boot-1",} 24927.0
    
    kafka_consumer_start_time_seconds{clientId="consumer-boot-1",} 1.615425258387E9
    
    kafka_consumer_successful_authentication_no_reauth_total{clientId="consumer-boot-1",} 0.0
    kafka_consumer_successful_authentication_total{clientId="consumer-boot-1",} 0.0
    kafka_consumer_successful_reauthentication_total{clientId="consumer-boot-1",} 0.0
    
    kafka_consumer_time_between_poll_avg{clientId="consumer-boot-1",} 999.5666666666667
    
    kafka_consumer_version_info{version="2.6.0",clientId="consumer-boot-1",} 1.0
    
    kafka_producer_batch_size_avg{clientId="producer-1",} 79.0
    kafka_producer_batch_split_total{clientId="producer-1",} 0.0
    
    kafka_producer_buffer_available_bytes{clientId="producer-1",} 3.3554432E7
    kafka_producer_buffer_exhausted_total{clientId="producer-1",} 0.0
    kafka_producer_buffer_total{clientId="producer-1",} 3.3554432E7
    
    kafka_producer_bufferpool_wait_ratio{clientId="producer-1",} 0.0
    kafka_producer_bufferpool_wait_time_total{clientId="producer-1",} 0.0
    
    kafka_producer_commit_id_info{commit_id="62abe01bee039651",clientId="producer-1",} 1.0
    
    kafka_producer_compression_rate_avg{clientId="producer-1",} 1.0
    
    kafka_producer_connection_close_total{clientId="producer-1",} 8.0
    kafka_producer_connection_count{clientId="producer-1",} 1.0
    kafka_producer_connection_creation_total{clientId="producer-1",} 2.0
    
    kafka_producer_failed_authentication_total{clientId="producer-1",} 0.0
    kafka_producer_failed_reauthentication_total{clientId="producer-1",} 0.0
    
    kafka_producer_incoming_byte_total{clientId="producer-1",} 144560.0
    
    kafka_producer_io_ratio{clientId="producer-1",} 2.100345345638304E-4
    kafka_producer_io_time_ns_avg{clientId="producer-1",} 69005.76923076923
    kafka_producer_io_wait_ratio{clientId="producer-1",} 1.0146865512935577
    kafka_producer_io_wait_time_ns_avg{clientId="producer-1",} 3.333765673076923E8
    kafka_producer_io_waittime_total{clientId="producer-1",} 2.2421980762E12
    kafka_producer_iotime_total{clientId="producer-1",} 5.488889E8
    
    kafka_producer_metadata_age{clientId="producer-1",} 184.642
    
    kafka_producer_network_io_total{clientId="producer-1",} 4472.0
    
    kafka_producer_node_incoming_byte_total{clientId="producer-1",nodeId="node--1",} 565.0
    kafka_producer_node_incoming_byte_total{clientId="producer-1",nodeId="node-0",} 143995.0
    
    kafka_producer_node_outgoing_byte_total{clientId="producer-1",nodeId="node--1",} 88.0
    kafka_producer_node_outgoing_byte_total{clientId="producer-1",nodeId="node-0",} 300826.0
    
    kafka_producer_node_request_latency_avg{clientId="producer-1",nodeId="node--1",} NaN
    kafka_producer_node_request_latency_avg{clientId="producer-1",nodeId="node-0",} 1.4333333333333333
    
    kafka_producer_node_request_size_avg{clientId="producer-1",nodeId="node--1",} NaN
    kafka_producer_node_request_size_avg{clientId="producer-1",nodeId="node-0",} 135.0
    
    kafka_producer_node_request_total{clientId="producer-1",nodeId="node--1",} 2.0
    kafka_producer_node_request_total{clientId="producer-1",nodeId="node-0",} 2234.0
    
    kafka_producer_node_response_total{clientId="producer-1",nodeId="node--1",} 2.0
    kafka_producer_node_response_total{clientId="producer-1",nodeId="node-0",} 2234.0
    
    kafka_producer_outgoing_byte_total{clientId="producer-1",} 300914.0
    
    kafka_producer_produce_throttle_time_avg{clientId="producer-1",} 0.0
    
    kafka_producer_reauthentication_latency_avg{clientId="producer-1",} NaN
    
    kafka_producer_record_error_total{clientId="producer-1",} 0.0
    kafka_producer_record_queue_time_avg{clientId="producer-1",} 0.3333333333333333
    kafka_producer_record_retry_total{clientId="producer-1",} 0.0
    kafka_producer_record_send_total{clientId="producer-1",} 2226.0
    kafka_producer_record_size_avg{clientId="producer-1",} 96.0
    
    kafka_producer_records_per_request_avg{clientId="producer-1",} 1.0
    
    kafka_producer_request_latency_avg{clientId="producer-1",} 1.4333333333333333
    kafka_producer_request_size_avg{clientId="producer-1",} 135.0
    kafka_producer_request_total{clientId="producer-1",} 2236.0
    
    kafka_producer_requests_in_flight{clientId="producer-1",} 0.0
    kafka_producer_response_total{clientId="producer-1",} 2236.0
    
    kafka_producer_select_total{clientId="producer-1",} 7042.0
    
    kafka_producer_start_time_seconds{clientId="producer-1",} 1.6154252697150002E9
    
    kafka_producer_successful_authentication_no_reauth_total{clientId="producer-1",} 0.0
    kafka_producer_successful_authentication_total{clientId="producer-1",} 0.0
    kafka_producer_successful_reauthentication_total{clientId="producer-1",} 0.0
    
    kafka_producer_topic_byte_total{clientId="producer-1",topic="Topic3",} 175854.0
    kafka_producer_topic_compression_rate{clientId="producer-1",topic="Topic3",} 1.0
    kafka_producer_topic_record_error_total{clientId="producer-1",topic="Topic3",} 0.0
    kafka_producer_topic_record_retry_total{clientId="producer-1",topic="Topic3",} 0.0
    kafka_producer_topic_record_send_total{clientId="producer-1",topic="Topic3",} 2226.0
    
    kafka_producer_version_info{version="2.6.0",clientId="producer-1",} 1.0
    
    kafka_producer_waiting_threads{clientId="producer-1",} 0.0
    
    process_cpu_seconds_total 61.82
    process_max_fds 1048576.0
    process_open_fds 50.0
    process_resident_memory_bytes 1.247813632E9
    process_start_time_seconds 1.615425251922E9
    process_virtual_memory_bytes 9.221738496E9