version: '3.9'
services:
  nodeserver:
    build:
      context: node-server
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
  nodejs-client:
    build: .
    ports:
    - "8090:8090"
    depends_on:
      nodeserver:
        condition: service_started

  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090


