apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "auth"
  namespace: {{ include "karte.namespace" . }}
spec:
  host: "auth"
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
