apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-karte"
  namespace: {{ include "karte.namespace" . }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: http
  {{- if .Values.multiEnv }}
  targetLabels:
    - asserts_env
    - asserts_site
  {{- end }}
