{{- if and (.Capabilities.APIVersions.Has "bitnami.com/v1alpha1") (.Values.tenant.auth.enabled) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.tenant.name }}-tsdb-remote-write
{{- if index .Values "kube-prometheus-stack" "namespaceOverride" }}
  namespace: {{ index .Values "kube-prometheus-stack" "namespaceOverride" }}
{{- else }}
  namespace: {{ .Release.Namespace }} 
{{- end }}
spec:
  encryptedData:
    password: {{ .Values.tenant.auth.password }}
    username: {{ .Values.tenant.auth.username }}
{{- end }}
