apiVersion: v1
kind: Service
metadata:
  name: "user"
  labels:
    {{- include "karte.labels" . | nindent 4 }}
    service: user
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "karte.selectorLabels" . | nindent 4 }}
    service: user
