#!/bin/bash

kubectx asserts-dev

kubens springboot-kafka-app

helm dep up .

helm upgrade --install orderverifier . \
  --set image.repository=543343501704.dkr.ecr.us-west-2.amazonaws.com/ai.asserts.springboot-kafka-app \
  --atomic \
  --debug \
  $*
