server:
  port: 8093
  servlet:
    context-path: "/ordercategorizer"

# enable Prometheus metrics
management:
  endpoint:
    prometheus:
      enabled: true
    web:
      exposure:
        include: "info, health, prometheus"
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot
    bootstrap-servers: kafka:9092


topic:
  consume: verifiedorders

