apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-kafka-app.fullname" . }}
  labels:
    {{- include "springboot-kafka-app.labels" . | nindent 4 }}
data:
  {{ include "config-map-contents" . }}
