apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-kafka-app.fullname" . }}
  labels:
    {{- include "springboot-kafka-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.springboot.port }}
      targetPort: http
      protocol: TCP
      name: springboot
    - port: {{ .Values.service.jmx.port }}
      targetPort: http
      protocol: TCP
      name: jmx
  selector:
    {{- include "springboot-kafka-app.selectorLabels" . | nindent 4 }}
